In [1]:
import tensorflow as tf
from tensorflow.examples.tutorials.mnist import input_data

In [4]:
###第二波改进增加多个命名空间



###载入数据集
mnist= input_data.read_data_sets('MNIST_data',one_hot=True)



###计算有多少批次
batch_size=100
n_batch = mnist.train.num_examples // batch_size



##来个函数
def variable_summariess(var):
    with tf.name_scope('summaries'):
        mean=tf.reduce_mean(var)
        tf.summary.scalar('mean',mean)
        with tf.name_scope('stddev'):
            stddev=tf.sqrt(tf.reduce_mean(tf.square(var-mean)))
        tf.summary.scalar('stddev',stddev)
        tf.summary.scalar('max',tf.reduce_max(var))
        tf.summary.scalar('min',tf.reduce_min(var))
        tf.summary.histogram('histogram',var)





###命名空间
with tf.name_scope('input'):
    ###定义连个placeholder
    x= tf.placeholder(tf.float32,[None,784],name='x_input')
    y= tf.placeholder(tf.float32,[None,10],name='y_input')
###创建一个简单的神经网络

with tf.name_scope('layer'):
    with tf.name_scope('Weight'):
        W= tf.Variable(tf.zeros([784,10]),name='Weight_1')
        variable_summariess(W)
    with tf.name_scope('biases'):
        b=tf.Variable(tf.zeros([10]))
        variable_summariess(b)
    with tf.name_scope('mut'):
        mut=tf.matmul(x,W)+b
    with tf.name_scope('prediction'):
        prediction= tf.nn.softmax(mut)


###二次代价函数
with tf.name_scope('loss'):
    
# loss= tf.reduce_mean(tf.square(y- prediction))
    loss=tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(labels=y,logits=prediction))
    tf.summary.scalar('loss',loss)
###使用梯度下降法
with tf.name_scope('train'):
    train= tf.train.GradientDescentOptimizer(0.2).minimize(loss)

###初始化变量
init= tf.global_variables_initializer()

with tf.name_scope('accuracy'):
    ###结果存在在一个布尔型的变量中
    ###tf.argmax是用来判断其中的最大值
    with tf.name_scope('correct_prediction'):
        correct_prediciton = tf.equal(tf.arg_max(y,1),tf.arg_max(prediction,1))
    ###求准确率
    ###tf.cast是用来转化的
    with tf.name_scope('accuracy'):
        accuracy = tf.reduce_mean(tf.cast(correct_prediciton,tf.float32))
        tf.summary.scalar('accuracy',accuracy)
        
###产生metadata文件
if tf.gfile.Exists(DeprecationWarning)
        
        
        
        
####合并所有的summary
merged=tf.summary.merge_all()
        
        
with tf.Session() as sess:
    sess.run(init)
    writer= tf.summary.FileWriter('logs/',sess.graph)
    for epoch in range(51):
        for batch in range(n_batch):
            ###首先获得一个批次，大小为100
            batch_xs,batch_ys= mnist.train.next_batch(batch_size)
            summary,_=sess.run([merged,train],feed_dict={x:batch_xs,y:batch_ys})
        writer.add_summary(summary,epoch)    
        acc=sess.run(accuracy,feed_dict={x:mnist.test.images,y:mnist.test.labels})
        print('Iter'+str(epoch)+'Testing Accuracy'+str(acc))

Extracting MNIST_data\train-images-idx3-ubyte.gz
Extracting MNIST_data\train-labels-idx1-ubyte.gz
Extracting MNIST_data\t10k-images-idx3-ubyte.gz
Extracting MNIST_data\t10k-labels-idx1-ubyte.gz
Iter0Testing Accuracy0.8474
Iter1Testing Accuracy0.8959
Iter2Testing Accuracy0.9023
Iter3Testing Accuracy0.9051
Iter4Testing Accuracy0.9084
Iter5Testing Accuracy0.9097
Iter6Testing Accuracy0.9124
Iter7Testing Accuracy0.9143
Iter8Testing Accuracy0.9147
Iter9Testing Accuracy0.9168
Iter10Testing Accuracy0.9184
Iter11Testing Accuracy0.9185
Iter12Testing Accuracy0.9184
Iter13Testing Accuracy0.9183
Iter14Testing Accuracy0.9204
Iter15Testing Accuracy0.9204
Iter16Testing Accuracy0.9206
Iter17Testing Accuracy0.9211
Iter18Testing Accuracy0.9212
Iter19Testing Accuracy0.9215
Iter20Testing Accuracy0.9214
Iter21Testing Accuracy0.9214
Iter22Testing Accuracy0.9217
Iter23Testing Accuracy0.9233
Iter24Testing Accuracy0.9226
Iter25Testing Accuracy0.9231
Iter26Testing Accuracy0.9236
Iter27Testing Accuracy0.923
Iter2

In [6]:
###为了看到更多的点可以使用
for i in range(2000)：
    batch_xs,batch_ys=mnist.train.next_batch(100)
    summary,_=sess.run([merged,train],feed_dict={x:batch_xs,y:batch_ys})
    writer.add_summary(summary,i)
    if i%500 == 0：
        print(sess.run(accuracy,feed_dict={x:mnist.test.images,y:mnist.test.labels}))

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.